apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fcp-vet-visits
  description: FCP Vet Visits
spec:
  type: team
  profile:
    displayName: FCP Vet Visits
    picture: https://avatars.githubusercontent.com/u/5528822?s=200&v=4
  parent: farming-countryside-programme
  children: []
