apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: fcp-demo
  description: FCP Demo
spec:
  type: team
  profile:
    displayName: FCP Demo
    email: fcp.demo@defra.gov.uk
    picture: https://avatars.githubusercontent.com/u/5528822?s=200&v=4
  parent: fcp
  children: []
