parameters:
- name: deployFromFeature
  displayName: "Deploy from Feature Branch"
  type: boolean
  default: false


pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/heads/main

extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    projectName: "FFCTemplateDocs"
    deployFromFeature: {% raw %}${{ parameters.deployFromFeature }}{% endraw %}
    # appBuildConfig:
    #   appFrameworkType: "nodejs"    
    #   projectPath: "./package.json"
    #   manifestPath: "./package.json"
    #   imageRepoName: "${{ values.project_name }}"
    # appTestConfig:
    #   testFilePath: "./docker-compose.test.yaml"
