apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: grants
  description: Everything related to grants
  title: FCP Grants
  links:
    - url: http://example.com/domain/grants/
      title: Domain Readme
    - url: http://example.com/domains/grants/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: fcp-grants