apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffc-demo-payments-db
  description: Payments service database
  tags:
    - postgresql
spec:
  type: database
  owner: "group:default/fcp-payments"
  system: ffc-demo-service
  dependsOn:
    - ffc-demo-database-server
