{{- include "adp-helm-library.container-secret" (list . "${{ values.project_name }}.container-secret") -}}
{{- define "${{ values.project_name }}.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
